server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://124.222.108.213:3306/talkso?useUnicode=true&characterEncoding=utf8
    username: talkso
    password: DEHyEhTmsWHCipXG
