server:
  port: 8081
  servlet:
    context-path: /dev

spring:
  datasource:
    url: jdbc:mysql://124.222.108.213:3306/talkso_dev?useUnicode=true&characterEncoding=utf8
    username: talkso_dev
    password: YzwYZDx2EKYbX2NH
